# 自动生成,请勿手改。改 养老院房间映射表.csv 后重新运行 生成HA配置.py
mqtt:
  sensor:
    - name: "101_人体距离"
      unique_id: "101_r60abd1_humanDistance"
      state_topic: "/Radar60SP/请在配网时登记设备ID/sys/property/post"
      value_template: "{{ value_json.params.humanDistance }}"
      unit_of_measurement: "cm"
      state_class: measurement
      device:
        identifiers: "r60abd1_101"
        name: "101房间睡眠雷达"
        manufacturer: "MicRadar"
        model: "R60ABD1"
        suggested_area: "101"
    - name: "101_体动幅度"
      unique_id: "101_r60abd1_movementSigns"
      state_topic: "/Radar60SP/请在配网时登记设备ID/sys/property/post"
      value_template: "{{ value_json.params.movementSigns }}"
      state_class: measurement
      device:
        identifiers: "r60abd1_101"
        name: "101房间睡眠雷达"
        manufacturer: "MicRadar"
        model: "R60ABD1"
        suggested_area: "101"
    - name: "101_呼吸数值"
      unique_id: "101_r60abd1_breathValue"
      state_topic: "/Radar60SP/请在配网时登记设备ID/sys/property/post"
      value_template: "{{ value_json.params.breathValue }}"
      unit_of_measurement: "次/分"
      state_class: measurement
      device:
        identifiers: "r60abd1_101"
        name: "101房间睡眠雷达"
        manufacturer: "MicRadar"
        model: "R60ABD1"
        suggested_area: "101"
    - name: "101_心率"
      unique_id: "101_r60abd1_heartRateValue"
      state_topic: "/Radar60SP/请在配网时登记设备ID/sys/property/post"
      value_template: "{{ value_json.params.heartRateValue }}"
      unit_of_measurement: "次/分"
      state_class: measurement
      device:
        identifiers: "r60abd1_101"
        name: "101房间睡眠雷达"
        manufacturer: "MicRadar"
        model: "R60ABD1"
        suggested_area: "101"
    - name: "101_睡眠状态"
      unique_id: "101_r60abd1_sleepStatus"
      state_topic: "/Radar60SP/请在配网时登记设备ID/sys/property/post"
      value_template: "{{ value_json.params.sleepStatus }}"
      device:
        identifiers: "r60abd1_101"
        name: "101房间睡眠雷达"
        manufacturer: "MicRadar"
        model: "R60ABD1"
        suggested_area: "101"
    - name: "101_睡眠评分"
      unique_id: "101_r60abd1_sleepScore"
      state_topic: "/Radar60SP/请在配网时登记设备ID/sys/property/post"
      value_template: "{{ value_json.params.sleepScore }}"
      state_class: measurement
      device:
        identifiers: "r60abd1_101"
        name: "101房间睡眠雷达"
        manufacturer: "MicRadar"
        model: "R60ABD1"
        suggested_area: "101"
    - name: "101_清醒时长"
      unique_id: "101_r60abd1_awakeDuration"
      state_topic: "/Radar60SP/请在配网时登记设备ID/sys/property/post"
      value_template: "{{ value_json.params.awakeDuration }}"
      unit_of_measurement: "分钟"
      state_class: measurement
      device:
        identifiers: "r60abd1_101"
        name: "101房间睡眠雷达"
        manufacturer: "MicRadar"
        model: "R60ABD1"
        suggested_area: "101"
    - name: "101卫生间_跌倒位置X"
      unique_id: "101卫生间_r60afd1_fallPosition_x"
      state_topic: "/Radar60FL/请在配网时登记设备ID/sys/property/post"
      value_template: "{{ value_json.params.fallPosition.x }}"
      unit_of_measurement: "cm"
      device:
        identifiers: "r60afd1_101卫生间"
        name: "101卫生间房间跌倒雷达"
        manufacturer: "MicRadar"
        model: "R60AFD1"
        suggested_area: "101卫生间"
    - name: "102_人体距离"
      unique_id: "102_r60abd1_humanDistance"
      state_topic: "/Radar60SP/请在配网时登记设备ID/sys/property/post"
      value_template: "{{ value_json.params.humanDistance }}"
      unit_of_measurement: "cm"
      state_class: measurement
      device:
        identifiers: "r60abd1_102"
        name: "102房间睡眠雷达"
        manufacturer: "MicRadar"
        model: "R60ABD1"
        suggested_area: "102"
    - name: "102_体动幅度"
      unique_id: "102_r60abd1_movementSigns"
      state_topic: "/Radar60SP/请在配网时登记设备ID/sys/property/post"
      value_template: "{{ value_json.params.movementSigns }}"
      state_class: measurement
      device:
        identifiers: "r60abd1_102"
        name: "102房间睡眠雷达"
        manufacturer: "MicRadar"
        model: "R60ABD1"
        suggested_area: "102"
    - name: "102_呼吸数值"
      unique_id: "102_r60abd1_breathValue"
      state_topic: "/Radar60SP/请在配网时登记设备ID/sys/property/post"
      value_template: "{{ value_json.params.breathValue }}"
      unit_of_measurement: "次/分"
      state_class: measurement
      device:
        identifiers: "r60abd1_102"
        name: "102房间睡眠雷达"
        manufacturer: "MicRadar"
        model: "R60ABD1"
        suggested_area: "102"
    - name: "102_心率"
      unique_id: "102_r60abd1_heartRateValue"
      state_topic: "/Radar60SP/请在配网时登记设备ID/sys/property/post"
      value_template: "{{ value_json.params.heartRateValue }}"
      unit_of_measurement: "次/分"
      state_class: measurement
      device:
        identifiers: "r60abd1_102"
        name: "102房间睡眠雷达"
        manufacturer: "MicRadar"
        model: "R60ABD1"
        suggested_area: "102"
    - name: "102_睡眠状态"
      unique_id: "102_r60abd1_sleepStatus"
      state_topic: "/Radar60SP/请在配网时登记设备ID/sys/property/post"
      value_template: "{{ value_json.params.sleepStatus }}"
      device:
        identifiers: "r60abd1_102"
        name: "102房间睡眠雷达"
        manufacturer: "MicRadar"
        model: "R60ABD1"
        suggested_area: "102"
    - name: "102_睡眠评分"
      unique_id: "102_r60abd1_sleepScore"
      state_topic: "/Radar60SP/请在配网时登记设备ID/sys/property/post"
      value_template: "{{ value_json.params.sleepScore }}"
      state_class: measurement
      device:
        identifiers: "r60abd1_102"
        name: "102房间睡眠雷达"
        manufacturer: "MicRadar"
        model: "R60ABD1"
        suggested_area: "102"
    - name: "102_清醒时长"
      unique_id: "102_r60abd1_awakeDuration"
      state_topic: "/Radar60SP/请在配网时登记设备ID/sys/property/post"
      value_template: "{{ value_json.params.awakeDuration }}"
      unit_of_measurement: "分钟"
      state_class: measurement
      device:
        identifiers: "r60abd1_102"
        name: "102房间睡眠雷达"
        manufacturer: "MicRadar"
        model: "R60ABD1"
        suggested_area: "102"
  binary_sensor:
    - name: "101_有人"
      unique_id: "101_r60abd1_someoneExists"
      state_topic: "/Radar60SP/请在配网时登记设备ID/sys/property/post"
      value_template: "{{ value_json.params.someoneExists }}"
      payload_on: "1"
      payload_off: "0"
      device_class: occupancy
      device:
        identifiers: "r60abd1_101"
        name: "101房间睡眠雷达"
        manufacturer: "MicRadar"
        model: "R60ABD1"
        suggested_area: "101"
    - name: "101_已上床"
      unique_id: "101_r60abd1_getIntoBed"
      state_topic: "/Radar60SP/请在配网时登记设备ID/sys/property/post"
      value_template: "{{ value_json.params.getIntoBed }}"
      payload_on: "1"
      payload_off: "0"
      device:
        identifiers: "r60abd1_101"
        name: "101房间睡眠雷达"
        manufacturer: "MicRadar"
        model: "R60ABD1"
        suggested_area: "101"
    - name: "101_在线"
      unique_id: "101_r60abd1_online"
      state_topic: "/Radar60SP/请在配网时登记设备ID/sys/property/post"
      value_template: "{{ value_json.params.online }}"
      payload_on: "1"
      payload_off: "0"
      device_class: connectivity
      device:
        identifiers: "r60abd1_101"
        name: "101房间睡眠雷达"
        manufacturer: "MicRadar"
        model: "R60ABD1"
        suggested_area: "101"
    - name: "101卫生间_跌倒报警"
      unique_id: "101卫生间_r60afd1_fallStatus"
      state_topic: "/Radar60FL/请在配网时登记设备ID/sys/property/post"
      value_template: "{{ value_json.params.fallStatus }}"
      payload_on: "1"
      payload_off: "0"
      device_class: safety
      device:
        identifiers: "r60afd1_101卫生间"
        name: "101卫生间房间跌倒雷达"
        manufacturer: "MicRadar"
        model: "R60AFD1"
        suggested_area: "101卫生间"
    - name: "101卫生间_静止驻留"
      unique_id: "101卫生间_r60afd1_residentStatus"
      state_topic: "/Radar60FL/请在配网时登记设备ID/sys/property/post"
      value_template: "{{ value_json.params.residentStatus }}"
      payload_on: "1"
      payload_off: "0"
      device:
        identifiers: "r60afd1_101卫生间"
        name: "101卫生间房间跌倒雷达"
        manufacturer: "MicRadar"
        model: "R60AFD1"
        suggested_area: "101卫生间"
    - name: "101卫生间_有人"
      unique_id: "101卫生间_r60afd1_someoneExists"
      state_topic: "/Radar60FL/请在配网时登记设备ID/sys/property/post"
      value_template: "{{ value_json.params.someoneExists }}"
      payload_on: "1"
      payload_off: "0"
      device_class: occupancy
      device:
        identifiers: "r60afd1_101卫生间"
        name: "101卫生间房间跌倒雷达"
        manufacturer: "MicRadar"
        model: "R60AFD1"
        suggested_area: "101卫生间"
    - name: "102_有人"
      unique_id: "102_r60abd1_someoneExists"
      state_topic: "/Radar60SP/请在配网时登记设备ID/sys/property/post"
      value_template: "{{ value_json.params.someoneExists }}"
      payload_on: "1"
      payload_off: "0"
      device_class: occupancy
      device:
        identifiers: "r60abd1_102"
        name: "102房间睡眠雷达"
        manufacturer: "MicRadar"
        model: "R60ABD1"
        suggested_area: "102"
    - name: "102_已上床"
      unique_id: "102_r60abd1_getIntoBed"
      state_topic: "/Radar60SP/请在配网时登记设备ID/sys/property/post"
      value_template: "{{ value_json.params.getIntoBed }}"
      payload_on: "1"
      payload_off: "0"
      device:
        identifiers: "r60abd1_102"
        name: "102房间睡眠雷达"
        manufacturer: "MicRadar"
        model: "R60ABD1"
        suggested_area: "102"
    - name: "102_在线"
      unique_id: "102_r60abd1_online"
      state_topic: "/Radar60SP/请在配网时登记设备ID/sys/property/post"
      value_template: "{{ value_json.params.online }}"
      payload_on: "1"
      payload_off: "0"
      device_class: connectivity
      device:
        identifiers: "r60abd1_102"
        name: "102房间睡眠雷达"
        manufacturer: "MicRadar"
        model: "R60ABD1"
        suggested_area: "102"
